baseURL = 'https://swissdatasciencecenter.github.io/renku-blog/'
languageCode = 'en-us'
title = 'Renku Blog'
theme = 'ananke'
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  site_logo = "img/logo.svg"
  custom_css = ["custom.css"]
  background_color_class = "renku-bg"
