# Workflow for testing the blog
name: Run Tests

on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
      - name: Install dependencies
        run: npm clean-install
      - name: Run format-check
        run: npm run format:check
      - name: Build site
        run: npm run build
