# Workflow for removing preview deployments of the blog
name: Undeploy blog preview

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

# Default to bash
defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Build job
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Uninstall helm chart
        env:
          RENKU_RELEASE: renku-blog-ci-${{ github.event.number }}
          KUBECONFIG: "${{ github.workspace }}/renkubot-kube.config"
          RENKUBOT_KUBECONFIG: ${{ secrets.RENKUBOT_DEV_KUBECONFIG }}
        run: |
          RENKU_NAMESPACE=${RENKU_RELEASE}
          echo "$RENKUBOT_KUBECONFIG" > "$KUBECONFIG" && chmod 400 "$KUBECONFIG"
          helm uninstall ${RENKU_RELEASE} --namespace=${RENKU_NAMESPACE} \
            --timeout 5m --wait
          kubectl delete namespace ${RENKU_NAMESPACE} || true
